#include <stdint.h>

#include "build.h"

uint8_t directions[8] = {
    DIR_DOWN,			// 'A'
    DIR_DOWN | DIR_RIGHT,	// 'B'
    DIR_RIGHT,			// 'C'
    DIR_RIGHT | DIR_UP,		// 'D'
    DIR_UP,			// 'E'
    DIR_UP | DIR_LEFT,		// 'F'
    DIR_LEFT,			// 'G'
    DIR_LEFT | DIR_DOWN,	// 'H'
};

#define SCROLL_STEP		1

#if ( SCROLL_STEP == 1 )

// path for 1-pixel scrolling
uint8_t scroll_path[] = {
/*
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"
    "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"
*/
/*
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
*/
/*
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"
*/
/*
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
*/
/*
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
*/

/*
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"
    "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"
*/
/*
    "ACACACACACACACACACACACACACACACACACAC"
*/
/*
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
*/
/*
    "CCCCCCCCCCCCCCCC"
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"
    "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"
*/
    // walls map walk
    "AAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC"
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"
    "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"
    "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"
    "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"
};

#elif ( SCROLL_STEP == 2 )

// path for 2-pixel scrolling
uint8_t scroll_path[] = {
    // walls map walk
    "AAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAA"
    "BBBBBBBBBBBBBBBB"
    "CCCCCCCCCCCCCCCC"
    "CCCCCCCCCCCCCCCC"
    "DDDDDDDDDDDDDDDD"
    "EEEEEEEEEEEEEEEE"
    "EEEEEEEEEEEEEEEE"
    "FFFFFFFFFFFFFFFF"
    "GGGGGGGGGGGGGGGG"
    "GGGGGGGGGGGGGGGG"
    "HHHHHHHHHHHHHHHH"
};

#elif ( SCROLL_STEP == 4 )

// path for 4-pixel scrolling
uint8_t scroll_path[] = {
    // walls map walk
    "AAAAAAAA"
    "AAAAAAAA"
    "BBBBBBBB"
    "CCCCCCCC"
    "CCCCCCCC"
    "DDDDDDDD"
    "EEEEEEEE"
    "EEEEEEEE"
    "FFFFFFFF"
    "GGGGGGGG"
    "GGGGGGGG"
    "HHHHHHHH"
};

#elif ( SCROLL_STEP == 8 )

// path for 8-pixel scrolling
uint8_t scroll_path[] = {
    // walls map walk
    "AAAA"
    "AAAA"
    "BBBB"
    "CCCC"
    "CCCC"
    "DDDD"
    "EEEE"
    "EEEE"
    "FFFF"
    "GGGG"
    "GGGG"
    "HHHH"
};

#else
    #error "SCROLL_STEP must be defined with value 1, 2, 4 or 8"
#endif
    
void main( void ) {
    static uint8_t *p,dir,kbd;

    init_perfmeter();
    init_screen_address_tables();
    init_tile_map();
    init_kbd();

    // horizontal checks
//    scroll_map_set_viewport_xy( 0, 0 );
//    scroll_map_set_viewport_xy( 0, 16 );
//    scroll_map_set_viewport_xy( 0, 32 );
//    scroll_map_set_viewport_xy( 0, 240 );
//    scroll_map_set_viewport_xy( 0, 256 );

    // vertical checks
//    scroll_map_set_viewport_xy( 0, 0 );
//    scroll_map_set_viewport_xy( 16, 0 );
//    scroll_map_set_viewport_xy( 32, 0 );
//    scroll_map_set_viewport_xy( 624, 0 );
//    scroll_map_set_viewport_xy( 640, 0 );

    // initial setup and draw
//    scroll_map_set_viewport_xy( 0, 48 );
    scroll_map_set_viewport_xy( 0, 32 );
    scroll_map_draw_viewport();

    reset_perfmeter();
    while (1) {

#if 0
        // either this loop: read kbd and scroll according to QAOP-SP
        kbd = kbd_read();
        dir = 0;
        dir |= ( kbd & in_UP ? DIR_UP : 0 );
        dir |= ( kbd & in_DOWN ? DIR_DOWN : 0 );
        dir |= ( kbd & in_LEFT ? DIR_LEFT : 0 );
        dir |= ( kbd & in_RIGHT ? DIR_RIGHT : 0 );
        if ( dir ) {
            scroll_map_scroll_viewport( dir, SCROLL_STEP );
            redraw_scroll_area();
        }
        do_perf_accounting();
        gotoxy(0,23); printf("D:%d",dir );
#else
        // or this other: read 'path' and run the walk encoded there
        p = scroll_path;
        while ( dir = *p++ ) {	// walk path
            scroll_map_scroll_viewport( directions[ dir - 'A'], SCROLL_STEP );
            redraw_scroll_area();
            do_perf_accounting();

        }
#endif
    } // loop forever
}
