#ifndef _CONFIG_H
#define _CONFIG_H

#define SCROLL_AREA_TOP		4
#define SCROLL_AREA_LEFT	8
#define SCROLL_AREA_WIDTH	16
#define SCROLL_AREA_HEIGHT	16
#define SCROLL_AREA_BOTTOM	( SCROLL_AREA_TOP + SCROLL_AREA_HEIGHT - 1 )
#define SCROLL_AREA_RIGHT	( SCROLL_AREA_LEFT + SCROLL_AREA_WIDTH - 1 )

#endif // _CONFIG_H
